#%RAML 1.0
title: project1withFirew
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/08c97aa5-dd44-4e16-af41-43ef97c34e2f
/name:
  post:
    description: this method is used to add name of user
    queryParameters:
      keyword:
        description: this is the query parameter which is requested 
        type: string
        required: true
        minLength: 3
        maxLength: 20
    responses:
        200:
            body:
                application/json:
                    example:
                     {"message": "Hello Kebede,welcome to Mulesoft,today is 20/06/2021"}
                                
